# Generated by Django 5.2.18 on 2026-10-07 06:17

import django.db.models.deletion
import django.utils.timezone
import edufinder.models.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='EstablishmentType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'establishment_type',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_exam', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='LinguisticSection',
            fields=[
                ('id_linguistic_section', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'linguistic_section',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id_payment_method', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('super_admin', 'Super Admin')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id_establishment', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=edufinder.models.identifiers.generate_public_uuid, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=120, null=True)),
                ('director_title', models.CharField(blank=True, max_length=80, null=True)),
                ('director_bio', models.TextField(blank=True, null=True)),
                ('director_photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended', models.BooleanField(db_default=False, default=False)),
                ('views_count', models.IntegerField(db_default=0, default=0)),
                ('inquiries_count', models.IntegerField(db_default=0, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='edufinder.city')),
                ('type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='edufinder.establishmenttype')),
                ('linguistic_section', models.ForeignKey(db_column='id_linguistic_section', on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='edufinder.linguisticsection')),
                ('sector', models.ForeignKey(db_column='id_sector', on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='edufinder.sector')),
            ],
            options={
                'db_table': 'establishment',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id_media', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('pdf', 'Pdf'), ('video', 'Video')], max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='media', to='edufinder.establishment')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id_program', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'program',
                'constraints': [models.UniqueConstraint(fields=('name',), name='uq_program_name')],
            },
        ),
        migrations.CreateModel(
            name='ProgramOffer',
            fields=[
                ('pk', models.CompositePrimaryKey('establishment_id', 'program_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='program_offers', to='edufinder.establishment')),
                ('program', models.ForeignKey(db_column='id_program', on_delete=django.db.models.deletion.PROTECT, related_name='establishment_offers', to='edufinder.program')),
            ],
            options={
                'db_table': 'program_offer',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'constraints': [models.UniqueConstraint(fields=('name',), name='uq_region_name')],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='edufinder.region'),
        ),
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id_fee', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('school_year', models.CharField(max_length=9)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='edufinder.establishment')),
            ],
            options={
                'db_table': 'school_fee',
            },
        ),
        migrations.CreateModel(
            name='SchoolFeePaymentMethod',
            fields=[
                ('pk', models.CompositePrimaryKey('fee_id', 'payment_method_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fee', models.ForeignKey(db_column='id_fee', on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='edufinder.schoolfee')),
                ('payment_method', models.ForeignKey(db_column='id_payment_method', on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='edufinder.paymentmethod')),
            ],
            options={
                'db_table': 'school_fee_payment_method',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='edufinder.establishment')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stage',
                'constraints': [models.UniqueConstraint(fields=('label',), name='uq_stage_label')],
            },
        ),
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id_level', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('stage', models.ForeignKey(db_column='id_stage', on_delete=django.db.models.deletion.PROTECT, related_name='study_levels', to='edufinder.stage')),
            ],
            options={
                'db_table': 'study_level',
            },
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='level',
            field=models.ForeignKey(db_column='id_level', on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='edufinder.studylevel'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id_submission', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=edufinder.models.identifiers.generate_public_uuid, max_length=36)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('creation', 'Creation'), ('modification', 'Modification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('content', models.JSONField()),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='edufinder.establishment')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='edufinder.user')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='EstablishmentStatusChange',
            fields=[
                ('id_status_change', models.AutoField(primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='edufinder.establishment')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='edufinder.user')),
            ],
            options={
                'db_table': 'establishment_status_change',
            },
        ),
        migrations.CreateModel(
            name='UserEstablishment',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'establishment_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='user_establishments', to='edufinder.establishment')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='user_establishments', to='edufinder.user')),
            ],
            options={
                'db_table': 'user_establishment',
            },
        ),
        migrations.CreateModel(
            name='ValidationDecision',
            fields=[
                ('id_decision', models.AutoField(primary_key=True, serialize=False)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('submission', models.OneToOneField(db_column='id_submission', on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='edufinder.submission')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='edufinder.user')),
            ],
            options={
                'db_table': 'validation_decision',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id_result', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=20)),
                ('pass_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='edufinder.establishment')),
                ('exam', models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='edufinder.exam')),
            ],
            options={
                'db_table': 'exam_result',
                'constraints': [models.UniqueConstraint(fields=('establishment', 'exam', 'session'), name='uq_exam_result_establishment_exam_session'), models.CheckConstraint(condition=models.Q(('pass_rate__gte', 0), ('pass_rate__lte', 100)), name='ck_exam_result_pass_rate_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='uq_city_name_region'),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(fields=('uuid',), name='uq_establishment_uuid'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('establishment', 'name'), name='uq_service_establishment_name'),
        ),
        migrations.AddConstraint(
            model_name='studylevel',
            constraint=models.UniqueConstraint(fields=('stage', 'label'), name='uq_study_level_stage_label'),
        ),
        migrations.AddConstraint(
            model_name='schoolfee',
            constraint=models.UniqueConstraint(fields=('establishment', 'level', 'school_year'), name='uq_fee_establishment_level_school_year'),
        ),
        migrations.AddConstraint(
            model_name='schoolfee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_school_fee_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('uuid',), name='uq_submission_uuid'),
        ),
    ]
