# Generated by Django 5.2.18 on 2026-10-07 13:25

import django.db.models.deletion
import django.utils.timezone
import edufinder.models.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=edufinder.models.identifiers.generate_public_uuid, max_length=36)),
                ('kind', models.CharField(choices=[('submission_received', 'Submission Received'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('establishment_suspended', 'Establishment Suspended'), ('establishment_reactivated', 'Establishment Reactivated')], max_length=40)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='edufinder.establishment')),
                ('recipient', models.ForeignKey(db_column='id_recipient', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='edufinder.user')),
                ('submission', models.ForeignKey(blank=True, db_column='id_submission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='edufinder.submission')),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='ix_notification_recipient')],
                'constraints': [models.UniqueConstraint(fields=('uuid',), name='uq_notification_uuid')],
            },
        ),
    ]
