# Generated by Django 5.2.18 on 2026-10-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufinder', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentDailyActivity',
            fields=[
                ('id_daily_activity', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
                ('inquiries_count', models.IntegerField(default=0)),
                ('establishment', models.ForeignKey(db_column='id_establishment', on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='edufinder.establishment')),
            ],
            options={
                'db_table': 'establishment_daily_activity',
                'constraints': [models.UniqueConstraint(fields=('establishment', 'day'), name='uq_daily_activity_establishment_day')],
            },
        ),
    ]
