# Generated by Django 5.2.18 on 2026-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufinder', '0007_merge_duplicate_reference_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='content_language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('en', 'English')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='description_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='director_bio_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='director_title_translation',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
